# Copyright (c) 2016 Intel Corporation

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:

# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Author: Clayne B. Robison <clayne dot b dot robison at intel dot com>

#THis Ansible play prepared the compute nodes to run the cloneImages.sh script found in ../scripts. It has the following tasks:
#   1. Copy the cloning script to the compute node
#   2. Verify that the HostVM-Master.xml domain definition file was present on the compute node in the correct location
#   3. Verify that the HostVM-master.qcow2 image was present on the compute node and in the correct location, and
#   4. Run the cloneImages.sh script
#This play assumes that the HostVM-Master domain definition file and qcow2 images are present on the compute node, and has the following input parameters:
#   provisioning_slave_dir: this is the directory on the remote node into which the script file is copied. This variable is defined in /etc/ansible/hosts.
#   provisioning_master_dir: this is the Ansible root directory on the Ansible controller. This variable is defined in /etc/ansible/hosts.
#See the cloneImages.sh script for more information
---
- hosts: all
  become: true
  vars: 
    sysprep_script_name: cloneImages.sh
    vm_xml_file: HostVM-Master.xml
    vm_image_file_path: /var/lib/libvirt/images/HostVM-Master.qcow2
  tasks: 
  - name: copy the cloning script
    copy: src={{ provisioning_master_dir }}/scripts/{{ sysprep_script_name }} dest={{ provisioning_slave_dir }}/{{ sysprep_script_name}} mode=0744
  - name: Ensure the HostVM-Master.xml file is present
    stat: path={{ provisioning_slave_dir }}/{{ vm_xml_file }}
    register: xml_stat_ret
  - name: Fail if XML isn't present
    fail: msg="{{ vm_xml_file }} not present"
    when: xml_stat_ret.stat.exists != True
  - name: Ensure the HostVM-Master.qcow2 image file is present
    stat: path={{ vm_image_file_path }}
    register: image_stat_ret
    become_user: root
    become_method: sudo
  - name: Fail if qcow2 image file isn't present
    fail: msg="{{ vm_image_file_path }} not present"
    when: image_stat_ret.stat.exists != True
  - name: Run the sysprep script
    command: "{{ provisioning_slave_dir }}/{{sysprep_script_name }}" 
    become_user: root
    become_method: sudo
...
